linters:
  enable-all: true
  disable:
    - deadcode
    - maligned
    - nosnakecase
    - scopelint
    - structcheck
    - ifshort
    - exhaustivestruct
    - varcheck
    - golint
    - interfacer
    - exhaustruct
    - varnamelen
    - nlreturn
    #  disabled because of generics.
    - rowserrcheck
    - sqlclosecheck
    - wastedassign
    #  disabled because own preference.
    - wsl
    - errchkjson
    - wrapcheck
